//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProteinTracker_Client.ProteinTrackerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://proteinTracker.ie/", ConfigurationName="ProteinTrackerService.ProteinTrackingServiceSoap")]
    public interface ProteinTrackingServiceSoap {
        
        // CODEGEN: Generating message contract since message AddProteinRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/AddProtein", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProteinTracker_Client.ProteinTrackerService.AddProteinResponse AddProtein(ProteinTracker_Client.ProteinTrackerService.AddProteinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/AddProtein", ReplyAction="*")]
        System.Threading.Tasks.Task<ProteinTracker_Client.ProteinTrackerService.AddProteinResponse> AddProteinAsync(ProteinTracker_Client.ProteinTrackerService.AddProteinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/AddUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddUser(string name, int goal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddUserAsync(string name, int goal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/ListUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProteinTracker_Client.ProteinTrackerService.User[] ListUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proteinTracker.ie/ListUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ProteinTracker_Client.ProteinTrackerService.User[]> ListUsersAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://proteinTracker.ie/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://proteinTracker.ie/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private string userNameField;
        
        private int goalField;
        
        private int totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
                this.RaisePropertyChanged("Goal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProtein", WrapperNamespace="http://proteinTracker.ie/", IsWrapped=true)]
    public partial class AddProteinRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://proteinTracker.ie/")]
        public ProteinTracker_Client.ProteinTrackerService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://proteinTracker.ie/", Order=0)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://proteinTracker.ie/", Order=1)]
        public int userId;
        
        public AddProteinRequest() {
        }
        
        public AddProteinRequest(ProteinTracker_Client.ProteinTrackerService.AuthenticationHeader AuthenticationHeader, int amount, int userId) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.amount = amount;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddProteinResponse", WrapperNamespace="http://proteinTracker.ie/", IsWrapped=true)]
    public partial class AddProteinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://proteinTracker.ie/", Order=0)]
        public int AddProteinResult;
        
        public AddProteinResponse() {
        }
        
        public AddProteinResponse(int AddProteinResult) {
            this.AddProteinResult = AddProteinResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProteinTrackingServiceSoapChannel : ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProteinTrackingServiceSoapClient : System.ServiceModel.ClientBase<ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap>, ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap {
        
        public ProteinTrackingServiceSoapClient() {
        }
        
        public ProteinTrackingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProteinTrackingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProteinTrackingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProteinTrackingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProteinTracker_Client.ProteinTrackerService.AddProteinResponse ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap.AddProtein(ProteinTracker_Client.ProteinTrackerService.AddProteinRequest request) {
            return base.Channel.AddProtein(request);
        }
        
        public int AddProtein(ProteinTracker_Client.ProteinTrackerService.AuthenticationHeader AuthenticationHeader, int amount, int userId) {
            ProteinTracker_Client.ProteinTrackerService.AddProteinRequest inValue = new ProteinTracker_Client.ProteinTrackerService.AddProteinRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.amount = amount;
            inValue.userId = userId;
            ProteinTracker_Client.ProteinTrackerService.AddProteinResponse retVal = ((ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap)(this)).AddProtein(inValue);
            return retVal.AddProteinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProteinTracker_Client.ProteinTrackerService.AddProteinResponse> ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap.AddProteinAsync(ProteinTracker_Client.ProteinTrackerService.AddProteinRequest request) {
            return base.Channel.AddProteinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProteinTracker_Client.ProteinTrackerService.AddProteinResponse> AddProteinAsync(ProteinTracker_Client.ProteinTrackerService.AuthenticationHeader AuthenticationHeader, int amount, int userId) {
            ProteinTracker_Client.ProteinTrackerService.AddProteinRequest inValue = new ProteinTracker_Client.ProteinTrackerService.AddProteinRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.amount = amount;
            inValue.userId = userId;
            return ((ProteinTracker_Client.ProteinTrackerService.ProteinTrackingServiceSoap)(this)).AddProteinAsync(inValue);
        }
        
        public int AddUser(string name, int goal) {
            return base.Channel.AddUser(name, goal);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string name, int goal) {
            return base.Channel.AddUserAsync(name, goal);
        }
        
        public ProteinTracker_Client.ProteinTrackerService.User[] ListUsers() {
            return base.Channel.ListUsers();
        }
        
        public System.Threading.Tasks.Task<ProteinTracker_Client.ProteinTrackerService.User[]> ListUsersAsync() {
            return base.Channel.ListUsersAsync();
        }
    }
}
